<a href="https://colab.research.google.com/github/Amro-source/Google-Colab/blob/main/Feed_forward_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import tensorflow as tf
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

RANDOM_SEED = 42
#tf.set_random_seed(RANDOM_SEED)
#import tensorflow.compat.v1 as tf

#tf.disable_v2_behavior()

def init_weights(shape):
    """ Weight initialization """
    weights = tf.random_normal(shape, stddev=0.1)
    return tf.Variable(weights)

def forwardprop(X, w_1, w_2):
    """
    Forward-propagation.
    IMPORTANT: yhat is not softmax since TensorFlow's softmax_cross_entropy_with_logits() does that internally.
    """
    h    = tf.nn.sigmoid(tf.matmul(X, w_1))  # The \sigma function
    yhat = tf.matmul(h, w_2)  # The \varphi function
    return yhat

def get_iris_data():
    """ Read the iris data set and split them into training and test sets """
    iris   = datasets.load_iris()
    data   = iris["data"]
    target = iris["target"]
    
    # Prepend the column of 1s for bias
    N, M  = data.shape
    all_X = np.ones((N, M + 1))
    all_X[:, 1:] = data

    # Convert into one-hot vectors
    num_labels = len(np.unique(target))
    all_Y = np.eye(num_labels)[target]  # One liner trick!
    return train_test_split(all_X, all_Y, test_size=0.33, random_state=RANDOM_SEED)

def main():
    train_X, test_X, train_y, test_y = get_iris_data()
    print("We are going to train a neural network")
    print("Be Patient")

    print ("We need to work hard on our data")
    # Layer's sizes
    x_size = train_X.shape[1]   # Number of input nodes: 4 features and 1 bias
    #print(x_size,shape[1])
    print("First we need to know X shape")
    print(train_X.shape[1]) 
    print(train_X.shape[0])
    print("Then wE need to know Y Shape")
    print(train_y.shape[1])
    print(train_y.shape[0])
    print(train_X)
    #print(train_y)

    h_size = 256                # Number of hidden nodes
    y_size = train_y.shape[1]   # Number of outcomes (3 iris flowers)
    
    # Symbols
    X = tf.placeholder("float", shape=[None, x_size])
    
    #X=tf.Variable(tf.ones(shape=[None, x_size]), dtype=tf.float32)

    y = tf.placeholder("float", shape=[None, y_size])

    #y=tf.Variable(tf.ones(shape=[None, y_size]), dtype=tf.float32)

    # Weight initializations
    w_1 = init_weights((x_size, h_size))
    w_2 = init_weights((h_size, y_size))

    # Forward propagation
    yhat    = forwardprop(X, w_1, w_2)
    predict = tf.argmax(yhat, axis=1)

    # Backward propagation
    cost    = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y, logits=yhat))
    updates = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

    # Run SGD
    sess = tf.Session()
    init = tf.global_variables_initializer()
    sess.run(init)

    for epoch in range(100):
        # Train with each example
        for i in range(len(train_X)):
            sess.run(updates, feed_dict={X: train_X[i: i + 1], y: train_y[i: i + 1]})

        train_accuracy = np.mean(np.argmax(train_y, axis=1) ==
                                 sess.run(predict, feed_dict={X: train_X, y: train_y}))
        test_accuracy  = np.mean(np.argmax(test_y, axis=1) ==
                                 sess.run(predict, feed_dict={X: test_X, y: test_y}))

        print("Epoch = %d, train accuracy = %.2f%%, test accuracy = %.2f%%"
              % (epoch + 1, 100. * train_accuracy, 100. * test_accuracy))

    sess.close()

if __name__ == '__main__':
    main()

We are going to train a neural network
Be Patient
We need to work hard on our data
First we need to know X shape
5
100
Then wE need to know Y Shape
3
100
[[1.  5.7 2.9 4.2 1.3]
 [1.  7.6 3.  6.6 2.1]
 [1.  5.6 3.  4.5 1.5]
 [1.  5.1 3.5 1.4 0.2]
 [1.  7.7 2.8 6.7 2. ]
 [1.  5.8 2.7 4.1 1. ]
 [1.  5.2 3.4 1.4 0.2]
 [1.  5.  3.5 1.3 0.3]
 [1.  5.1 3.8 1.9 0.4]
 [1.  5.  2.  3.5 1. ]
 [1.  6.3 2.7 4.9 1.8]
 [1.  4.8 3.4 1.9 0.2]
 [1.  5.  3.  1.6 0.2]
 [1.  5.1 3.3 1.7 0.5]
 [1.  5.6 2.7 4.2 1.3]
 [1.  5.1 3.4 1.5 0.2]
 [1.  5.7 3.  4.2 1.2]
 [1.  7.7 3.8 6.7 2.2]
 [1.  4.6 3.2 1.4 0.2]
 [1.  6.2 2.9 4.3 1.3]
 [1.  5.7 2.5 5.  2. ]
 [1.  5.5 4.2 1.4 0.2]
 [1.  6.  3.  4.8 1.8]
 [1.  5.8 2.7 5.1 1.9]
 [1.  6.  2.2 4.  1. ]
 [1.  5.4 3.  4.5 1.5]
 [1.  6.2 3.4 5.4 2.3]
 [1.  5.5 2.3 4.  1.3]
 [1.  5.4 3.9 1.7 0.4]
 [1.  5.  2.3 3.3 1. ]
 [1.  6.4 2.7 5.3 1.9]
 [1.  5.  3.3 1.4 0.2]
 [1.  5.  3.2 1.2 0.2]
 [1.  5.5 2.4 3.8 1.1]
 [1.  6.7 3.  5.  1.7]
 [1.  4.9 3.1 1.5 0.2]
 [1.  5.8 2.8 5.1 

In [ ]:
pip install tensorflow==1.4.0

In [ ]:
import tensorflow as tf

# first, create a TensorFlow constant
const = tf.constant(2.0, name="const")
    
# create TensorFlow variables
b = tf.Variable(2.0, name='b')
c = tf.Variable(1.0, name='c')

print(b)
print(c)

# now create some operations
d = tf.add(b, c, name='d')
e = tf.add(c, const, name='e')
a = tf.multiply(d, e, name='a')


# setup the variable initialisation
#init_op = tf.global_variables_initializer()

In [ ]:
!pip install tensorflow==1.12.0
import tensorflow as tf
print(tf.__version__)

In [2]:
import tensorflow as tf
print(tf.__version__)

1.12.0
